// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ponchik327/subscriptions-service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/ponchik327/subscriptions-service/internal/service"

	uuid "github.com/google/uuid"
)

// MockSubscriptionService is an autogenerated mock type for the SubscriptionService type
type MockSubscriptionService struct {
	mock.Mock
}

type MockSubscriptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionService) EXPECT() *MockSubscriptionService_Expecter {
	return &MockSubscriptionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionService) Create(ctx context.Context, sub domain.Subscription) (domain.Subscription, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) (domain.Subscription, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) domain.Subscription); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionService_Expecter) Create(ctx interface{}, sub interface{}) *MockSubscriptionService_Create_Call {
	return &MockSubscriptionService_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockSubscriptionService_Create_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionService_Create_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionService_Create_Call) RunAndReturn(run func(context.Context, domain.Subscription) (domain.Subscription, error)) *MockSubscriptionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionService_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionService_Delete_Call {
	return &MockSubscriptionService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionService_Delete_Call) Return(_a0 error) *MockSubscriptionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSubscriptionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionService) GetByID(ctx context.Context, id uuid.UUID) (domain.Subscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Subscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Subscription); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionService_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionService_GetByID_Call {
	return &MockSubscriptionService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionService_GetByID_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.Subscription, error)) *MockSubscriptionService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockSubscriptionService) List(ctx context.Context, filter domain.ListFilter) ([]domain.Subscription, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListFilter) ([]domain.Subscription, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListFilter) []domain.Subscription); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubscriptionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ListFilter
func (_e *MockSubscriptionService_Expecter) List(ctx interface{}, filter interface{}) *MockSubscriptionService_List_Call {
	return &MockSubscriptionService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSubscriptionService_List_Call) Run(run func(ctx context.Context, filter domain.ListFilter)) *MockSubscriptionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListFilter))
	})
	return _c
}

func (_c *MockSubscriptionService_List_Call) Return(_a0 []domain.Subscription, _a1 error) *MockSubscriptionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionService_List_Call) RunAndReturn(run func(context.Context, domain.ListFilter) ([]domain.Subscription, error)) *MockSubscriptionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Summary provides a mock function with given fields: ctx, p
func (_m *MockSubscriptionService) Summary(ctx context.Context, p service.SummaryParams) (domain.SummaryResult, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Summary")
	}

	var r0 domain.SummaryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.SummaryParams) (domain.SummaryResult, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.SummaryParams) domain.SummaryResult); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(domain.SummaryResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.SummaryParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionService_Summary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summary'
type MockSubscriptionService_Summary_Call struct {
	*mock.Call
}

// Summary is a helper method to define mock.On call
//   - ctx context.Context
//   - p service.SummaryParams
func (_e *MockSubscriptionService_Expecter) Summary(ctx interface{}, p interface{}) *MockSubscriptionService_Summary_Call {
	return &MockSubscriptionService_Summary_Call{Call: _e.mock.On("Summary", ctx, p)}
}

func (_c *MockSubscriptionService_Summary_Call) Run(run func(ctx context.Context, p service.SummaryParams)) *MockSubscriptionService_Summary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.SummaryParams))
	})
	return _c
}

func (_c *MockSubscriptionService_Summary_Call) Return(_a0 domain.SummaryResult, _a1 error) *MockSubscriptionService_Summary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionService_Summary_Call) RunAndReturn(run func(context.Context, service.SummaryParams) (domain.SummaryResult, error)) *MockSubscriptionService_Summary_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionService) Update(ctx context.Context, sub domain.Subscription) (domain.Subscription, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) (domain.Subscription, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) domain.Subscription); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionService_Expecter) Update(ctx interface{}, sub interface{}) *MockSubscriptionService_Update_Call {
	return &MockSubscriptionService_Update_Call{Call: _e.mock.On("Update", ctx, sub)}
}

func (_c *MockSubscriptionService_Update_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionService_Update_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionService_Update_Call) RunAndReturn(run func(context.Context, domain.Subscription) (domain.Subscription, error)) *MockSubscriptionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionService creates a new instance of MockSubscriptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionService {
	mock := &MockSubscriptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
