// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ponchik327/subscriptions-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionRepository) Create(ctx context.Context, sub domain.Subscription) (domain.Subscription, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) (domain.Subscription, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) domain.Subscription); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionRepository_Expecter) Create(ctx interface{}, sub interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Subscription) (domain.Subscription, error)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionRepository_Delete_Call {
	return &MockSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) Return(_a0 error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Subscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Subscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Subscription); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionRepository_GetByID_Call {
	return &MockSubscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.Subscription, error)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockSubscriptionRepository) List(ctx context.Context, filter domain.ListFilter) ([]domain.Subscription, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListFilter) ([]domain.Subscription, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListFilter) []domain.Subscription); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubscriptionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ListFilter
func (_e *MockSubscriptionRepository_Expecter) List(ctx interface{}, filter interface{}) *MockSubscriptionRepository_List_Call {
	return &MockSubscriptionRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSubscriptionRepository_List_Call) Run(run func(ctx context.Context, filter domain.ListFilter)) *MockSubscriptionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListFilter))
	})
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) Return(_a0 []domain.Subscription, _a1 error) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) RunAndReturn(run func(context.Context, domain.ListFilter) ([]domain.Subscription, error)) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Summary provides a mock function with given fields: ctx, f
func (_m *MockSubscriptionRepository) Summary(ctx context.Context, f domain.SummaryFilter) (int64, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Summary")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SummaryFilter) (int64, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SummaryFilter) int64); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SummaryFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Summary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summary'
type MockSubscriptionRepository_Summary_Call struct {
	*mock.Call
}

// Summary is a helper method to define mock.On call
//   - ctx context.Context
//   - f domain.SummaryFilter
func (_e *MockSubscriptionRepository_Expecter) Summary(ctx interface{}, f interface{}) *MockSubscriptionRepository_Summary_Call {
	return &MockSubscriptionRepository_Summary_Call{Call: _e.mock.On("Summary", ctx, f)}
}

func (_c *MockSubscriptionRepository_Summary_Call) Run(run func(ctx context.Context, f domain.SummaryFilter)) *MockSubscriptionRepository_Summary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SummaryFilter))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Summary_Call) Return(_a0 int64, _a1 error) *MockSubscriptionRepository_Summary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Summary_Call) RunAndReturn(run func(context.Context, domain.SummaryFilter) (int64, error)) *MockSubscriptionRepository_Summary_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionRepository) Update(ctx context.Context, sub domain.Subscription) (domain.Subscription, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) (domain.Subscription, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) domain.Subscription); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(ctx interface{}, sub interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", ctx, sub)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(_a0 domain.Subscription, _a1 error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(context.Context, domain.Subscription) (domain.Subscription, error)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
